# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from quickstart.grpc import quickstart_pb2 as quickstart_dot_grpc_dot_quickstart__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in quickstart/grpc/quickstart_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/todos.quickstart.PostController/Create',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/todos.quickstart.PostController/Destroy',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/todos.quickstart.PostController/List',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostListRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/todos.quickstart.PostController/PartialUpdate',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostPartialUpdateRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/todos.quickstart.PostController/Retrieve',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRetrieveRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/todos.quickstart.PostController/Update',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
                _registered_method=True)


class PostControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostListRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostPartialUpdateRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRetrieveRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todos.quickstart.PostController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todos.quickstart.PostController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/Create',
            quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/Destroy',
            quickstart_dot_grpc_dot_quickstart__pb2.PostDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/List',
            quickstart_dot_grpc_dot_quickstart__pb2.PostListRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/PartialUpdate',
            quickstart_dot_grpc_dot_quickstart__pb2.PostPartialUpdateRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/Retrieve',
            quickstart_dot_grpc_dot_quickstart__pb2.PostRetrieveRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.PostController/Update',
            quickstart_dot_grpc_dot_quickstart__pb2.PostRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserActionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/todos.quickstart.UserActionController/Create',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/todos.quickstart.UserActionController/Destroy',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/todos.quickstart.UserActionController/List',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/todos.quickstart.UserActionController/PartialUpdate',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserPartialUpdateRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/todos.quickstart.UserActionController/Retrieve',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/todos.quickstart.UserActionController/Update',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
                _registered_method=True)


class UserActionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserActionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserPartialUpdateRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todos.quickstart.UserActionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todos.quickstart.UserActionController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserActionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/Create',
            quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/Destroy',
            quickstart_dot_grpc_dot_quickstart__pb2.UserDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/List',
            quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/PartialUpdate',
            quickstart_dot_grpc_dot_quickstart__pb2.UserPartialUpdateRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/Retrieve',
            quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserActionController/Update',
            quickstart_dot_grpc_dot_quickstart__pb2.UserRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/todos.quickstart.UserController/List',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/todos.quickstart.UserController/Retrieve',
                request_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.SerializeToString,
                response_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
                _registered_method=True)


class UserControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.FromString,
                    response_serializer=quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todos.quickstart.UserController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todos.quickstart.UserController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserController/List',
            quickstart_dot_grpc_dot_quickstart__pb2.UserListRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.quickstart.UserController/Retrieve',
            quickstart_dot_grpc_dot_quickstart__pb2.UserRetrieveRequest.SerializeToString,
            quickstart_dot_grpc_dot_quickstart__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
